name: Pipeline
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Code Linting
        run: |
          npm run lint
        env:
          CI: ""